[win]
172.16.138.183
172.16.138.149
172.16.138.171

[win:vars]
ansible_user=<YOUR_USERNAME>
ansible_password=<YOUR_PASSWORD>
ansible_connection=winrm
ansible_winrm_transport=credssp
ansible_winrm_server_cert_validation=ignore
